# mongodb connection string for the main database
mongo="mongodb://$MONGO_HOST:$MONGO_PORT/wildduck"

# redis connection string to connect to a single master (see below for Sentinel example)
redis="redis://$REDIS_HOST:REDIS_PORT/3"

# WildDuck allows using different kind of data in different databases
# If you do not provide a database config value, then main database connection
# is used for everything
# You can either use a database name (uses shared connection) or a configutaion
# url (creates a separate connection) for each databases

# Optional database name or connection url for GridFS if you do not want to
# use the main db for storing attachments. Useful if you want
# to use a different mount folder or storage engine
#gridfs="wildduck"

# Optional database name or connection url for users collection if you do not want to
# use the main db for storing user/address data. Useful if you want
# to use a different mount folder or storage engine
#users="wildduck"

# Optional database name or connection url for ZoneMTA queue database. This is
# used to push outbound emails to the sending queue
sender="zone-mta"

#queued="mail"

[redis]
host="$REDIS_HOST"
port=$REDIS_PORT
db=3
